language: node_js
node_js:
  - 6 # LTS
  - 7 #
  - 8 # latest
services: redis
sudo: false
script: npm test
install:
  - npm update -g npm; npm install; ls node_modules/ | wc -l; ls -d node_modules/irc-socket
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
