language: node_js
node_js:
  - 10
  - 12
  - 13
services: redis-server
sudo: false
script:
  - yarn run install && yarn run test
install:
  - npm update npm -g && npm install -g lerna yarn && lerna bootstrap
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8